In [1]:
print("all ok")

all ok


In [2]:
import pandas as pd

In [3]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})


In [4]:

data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [6]:
#now pip install scikit-learn in command prompt and then do the below

from sklearn.feature_extraction.text import CountVectorizer


In [7]:
BOW=CountVectorizer() #converts a collection of documents to matrix of token counts(ie,Bag of Words)

In [ ]:
data["text"] #gives me documents

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [10]:
document_matrix=BOW.fit_transform(data["text"]) #it gives documnet matrix
document_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [ ]:
BOW.vocabulary_

#this is my Bag of Words with UNIGRAM

#the index is assignes based on alphabetical order ,as seen below

# { 'word:index', etc}

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

In [ ]:
document_matrix[0].toarray()#this gives the VECTOR of the first document/sentence ie)BOW


array([[0, 1, 0, 1, 1]])

In [ ]:
document_matrix[2].toarray()#this gives the vector of th third document/sentence ie)BOW

array([[1, 0, 1, 1, 0]])

In [ ]:
''' Home Work
Implement OHE for the below data using ANY library(for example numpy, pandas, tf, pytorch etc...)
after completeing this tag me and krish sir and send your solution in group chat
in next class i will give you the quick overview of it'''

In [ ]:
# N -GRAM   for that i have to crete an object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

##CountVectorizer basically captures the information in sequence,
# its not going to jump the word in btw,,,for jumping the words in btw, i have to write my own logic

In [26]:

data["text"] ##it shows in which index document s are assigned



0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [27]:
bigram=CountVectorizer(ngram_range=(2,2)) #bifram means 2 piar of words
#that you want to extract bigrams (2-grams) from the text.

#countvectorizer basically captures the information in sequence

bigramvocab=bigram.fit_transform(data["text"])


In [ ]:
bigram.vocabulary_ 
####this is my Bag Of Words with BIGRAMS


 #creates a pair of 2 words as below  ,

#uniq vocab from the above data  looks like this internally
# [('cricket give'),('cricket watch'),('give comment'),('people give'),('people watch'),('watch cricket')]

#0,1,2,3 refers to the index based on the alphabetical order




{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

In [ ]:
'''explaination of above  2 cells

bigram->: This variable is presumably an instance of CountVectorizer (or a similar vectorizer) that has been configured to extract bigrams.

data["text"]->: This part refers to a column named "text" in a DataFrame (likely a pandas DataFrame). The data variable is expected to be a DataFrame that contains text data. The "text" column contains the actual text documents from which you want to extract bigrams.'

fit_transform(...): This method does two things:

    Fit->: It learns the vocabulary of the bigrams from the provided text data. This means it identifies all the unique bigrams present in the text.

    Transform->: It converts the text data into a matrix of token counts (in this case, counts of bigrams). Each row in the resulting matrix corresponds to a document, and each column corresponds to a unique bigram. The values in the matrix represent the count of each bigram in each document.
'''

In [ ]:
trigram=CountVectorizer(ngram_range=(3,3)) #bifram means 2 piar of words

trigram.fit_transform(data["text"])

trigram.vocabulary_
####this gives my Bag Of Words with TRIGRAMS

{'people watch cricket': 3,
 'cricket watch cricket': 1,
 'people give comment': 2,
 'cricket give comment': 0}

In [ ]:
#now lets see MIX Grams


In [ ]:
mix=CountVectorizer(ngram_range=(1,3))
#here both Unigram and bigrams and trigrams  will be shown in sequentialorder without jumping and the biggest advantage is here the  context will be obtained

mix.fit_transform(data["text"])

mix.vocabulary_


{'people': 8,
 'watch': 13,
 'cricket': 1,
 'people watch': 11,
 'watch cricket': 14,
 'people watch cricket': 12,
 'cricket watch': 4,
 'cricket watch cricket': 5,
 'give': 6,
 'comment': 0,
 'people give': 9,
 'give comment': 7,
 'people give comment': 10,
 'cricket give': 2,
 'cricket give comment': 3}

In [ ]:
#Aim of encoding and encoding was to convert data into vectors(numerical representation of data)  

In [ ]:
#TF-IDF->invented by google

#Term-Frequency means occurance of word in a document

'''
TF of a word =
occurance of word in document/total words in that document
'''

#Inverse Document Frequency

'''
IDF of word =
log(
No of  total documents/
no of documents containing this word
)

log helps normalise the values


'''

'''
to convert data into encoding involves converting into vectors

step1)obtain vocabulary from the data



so corpus->documents->inside each document we can get a specific number for each word using TF*IDF formula and at the end we can get to know the importance of each word based on that number '''

In [ ]:
'''
TF-> gives Importance in a given sentence or document

IDF->It shows the uniqueness of a word across all sentences

log-> to compress or normalise the IDF value or reduce the skewness in IDF value

TF*IDF-> we are reducing the weightage of more common word and giving imp to unique/rare words



+ves->simple,context,unique words prioritsed

-ves-> Out of Vocabulary still remains,also little spearsity remains
'''

In [ ]:
#so we are importing TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer


In [32]:
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [33]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [ ]:
tfidf=TfidfVectorizer()
#creating object of TF-IDF


tfidf.fit_transform(data["text"]).toarray()  
#this gives me the TF_IDF vector for given data,basically number for each word which states the importance in the document 

array([[0.        , 0.49681612, 0.        , 0.61366674, 0.61366674],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357],
       [0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.61366674, 0.49681612, 0.61366674, 0.        , 0.        ]])

In [ ]:

feature_names = tfidf.get_feature_names_out()

print("Feature Names:", feature_names) #will give me the vocabulary

Feature Names: ['comment' 'cricket' 'give' 'people' 'watch']


In [36]:
tfidf.idf_ #gives the idf value for each of the unique words in the vocabulary

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])