In [1]:
print("all ok")

all ok


In [3]:
import torch

In [4]:
print(torch.__version__)

2.6.0+cpu


In [9]:
a=torch.empty(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
type(a)

torch.Tensor

In [10]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.rand(2,3)

tensor([[0.5910, 0.9614, 0.1271],
        [0.9992, 0.1722, 0.2429]])

In [12]:
torch.rand(2,3)

tensor([[0.2174, 0.2451, 0.0747],
        [0.4978, 0.0828, 0.7175]])

In [15]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
torch.arange(10,34)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33])

In [19]:
torch.arange(10,23,2)

tensor([10, 12, 14, 16, 18, 20, 22])

In [20]:
torch.linspace(0,1,20)

tensor([0.0000, 0.0526, 0.1053, 0.1579, 0.2105, 0.2632, 0.3158, 0.3684, 0.4211,
        0.4737, 0.5263, 0.5789, 0.6316, 0.6842, 0.7368, 0.7895, 0.8421, 0.8947,
        0.9474, 1.0000])

In [21]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [24]:
x=torch.tensor([[1,2,3],[5,6,7]])

In [25]:
x.shape

torch.Size([2, 3])

In [26]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [27]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.5837, 0.7650, 0.6946],
        [0.6973, 0.5092, 0.5785]])

In [28]:
x

tensor([[1, 2, 3],
        [5, 6, 7]])

In [29]:
x+2

tensor([[3, 4, 5],
        [7, 8, 9]])

In [31]:
x*3

tensor([[ 3,  6,  9],
        [15, 18, 21]])